Boxxer: boxxer::Boxxer2D< FloatT, IdxT > Class Template Reference
boxxer::Boxxer2D< FloatT, IdxT > Class Template Reference
#include </home/travis/build/markjolah/Boxxer/include/Boxxer/Boxxer2D.h>
Public Types
using IVecT = arma::Col< IdxT >
using IMatT = arma::Mat< IdxT >
using VecT = arma::Col< FloatT >
using MatT = arma::Mat< FloatT >
using ImageT = arma::Mat< FloatT >
using ImageStackT = arma::Cube< FloatT >
using ScaledImageT = arma::Cube< FloatT >
using ScaledImageStackT = hypercube::Hypercube< FloatT >
Public Member Functions
Boxxer2D (const IVecT &imsize, const MatT &sigma)
void setDoGSigmaRatio (FloatT sigma_ratio)
void filterScaledLoG (const ImageStackT &im, ScaledImageStackT &fim) const
void filterScaledDoG (const ImageStackT &im, ScaledImageStackT &fim) const
IdxT scaleSpaceLoGMaxima (const ImageStackT &im, IMatT &maxima, VecT &max_vals, IdxT neighborhood_size, IdxT scale_neighborhood_size) const
IdxT scaleSpaceDoGMaxima (const ImageStackT &im, IMatT &maxima, VecT &max_vals, IdxT neighborhood_size, IdxT scale_neighborhood_size) const
ImageT make_image () const
ImageStackT make_image_stack (IdxT nT) const
ScaledImageT make_scaled_image () const
ScaledImageStackT make_scaled_image_stack (IdxT nT) const
Static Public Member Functions
static void filterLoG (const ImageStackT &im, ImageStackT &fim, const VecT &sigma)
static void filterDoG (const ImageStackT &im, ImageStackT &fim, const VecT &sigma, FloatT sigma_ratio)
static void filterGauss (const ImageStackT &im, ImageStackT &fim, const VecT &sigma)
static void checkMaxima (const ImageStackT &im, IMatT &maxima, VecT &max_vals)
static IdxT enumerateImageMaxima (const ImageStackT &im, IMatT &maxima, VecT &max_vals, IdxT neighborhood_size)
Public Attributes
IdxT nScales
IVecT imsize
MatT sigma
FloatT sigma_ratio
Static Public Attributes
static const FloatT DefaultSigmaRatio
static const IdxT dim
Detailed Description
template<class FloatT = float, class IdxT = uint32_t>
class boxxer::Boxxer2D< FloatT, IdxT >
In this class we make the assumption that images are stored in column-major format and that x=rows, y=cols, t=slices. This relationship is important in the choice of imsize and sigma parameters.
imsize = [nrows, ncols, nframes]; sigma = [ sigma_rows (X scale=1), sigma_rows (X scale=2); sigma_cols(Y scale=1), sigma_cols (Y scale=2)]
This is contrary to normal image coordinates in matlab, but for this low level it is easier to think about x as the first index into an image and understand that the meaning for "X" and "Y" will be reversed from the matlab interpretation, but only internally within the Boxxer_IFace MexIFace class.
Definition at line 33 of file Boxxer2D.h.
Member Typedef Documentation
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer2D< FloatT, IdxT >::ImageStackT = arma::Cube<FloatT>
Definition at line 41 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer2D< FloatT, IdxT >::ImageT = arma::Mat<FloatT>
Definition at line 40 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer2D< FloatT, IdxT >::IMatT = arma::Mat<IdxT>
Definition at line 37 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer2D< FloatT, IdxT >::IVecT = arma::Col<IdxT>
Definition at line 36 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer2D< FloatT, IdxT >::MatT = arma::Mat<FloatT>
Definition at line 39 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer2D< FloatT, IdxT >::ScaledImageStackT = hypercube::Hypercube<FloatT>
Definition at line 43 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer2D< FloatT, IdxT >::ScaledImageT = arma::Cube<FloatT>
Definition at line 42 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer2D< FloatT, IdxT >::VecT = arma::Col<FloatT>
Definition at line 38 of file Boxxer2D.h.
Constructor & Destructor Documentation
template<class FloatT = float, class IdxT = uint32_t> boxxer::Boxxer2D< FloatT, IdxT >::Boxxer2D (const IVecT & imsize, const MatT & sigma)
Member Function Documentation
template<class FloatT = float, class IdxT = uint32_t> static void boxxer::Boxxer2D< FloatT, IdxT >::checkMaxima (const ImageStackT & im, IMatT & maxima, VecT & max_vals) static
Referenced by boxxer::Boxxer2D< FloatT, IdxT >::make_scaled_image_stack().
template<class FloatT = float, class IdxT = uint32_t> static IdxT boxxer::Boxxer2D< FloatT, IdxT >::enumerateImageMaxima (const ImageStackT & im, IMatT & maxima, VecT & max_vals, IdxT neighborhood_size) static
Referenced by boxxer::Boxxer2D< FloatT, IdxT >::make_scaled_image_stack().
template<class FloatT = float, class IdxT = uint32_t> static void boxxer::Boxxer2D< FloatT, IdxT >::filterDoG (const ImageStackT & im, ImageStackT & fim, const VecT & sigma, FloatT sigma_ratio) static
Referenced by boxxer::Boxxer2D< FloatT, IdxT >::make_scaled_image_stack().
template<class FloatT = float, class IdxT = uint32_t> static void boxxer::Boxxer2D< FloatT, IdxT >::filterGauss (const ImageStackT & im, ImageStackT & fim, const VecT & sigma) static
Referenced by boxxer::Boxxer2D< FloatT, IdxT >::make_scaled_image_stack().
template<class FloatT = float, class IdxT = uint32_t> static void boxxer::Boxxer2D< FloatT, IdxT >::filterLoG (const ImageStackT & im, ImageStackT & fim, const VecT & sigma) static
Referenced by boxxer::Boxxer2D< FloatT, IdxT >::make_scaled_image_stack().
template<class FloatT = float, class IdxT = uint32_t> void boxxer::Boxxer2D< FloatT, IdxT >::filterScaledDoG (const ImageStackT & im, ScaledImageStackT & fim) const
template<class FloatT = float, class IdxT = uint32_t> void boxxer::Boxxer2D< FloatT, IdxT >::filterScaledLoG (const ImageStackT & im, ScaledImageStackT & fim) const
template<class FloatT = float, class IdxT = uint32_t> ImageT boxxer::Boxxer2D< FloatT, IdxT >::make_image () const inline
Definition at line 61 of file Boxxer2D.h.
References boxxer::Boxxer2D< FloatT, IdxT >::imsize.
template<class FloatT = float, class IdxT = uint32_t> ImageStackT boxxer::Boxxer2D< FloatT, IdxT >::make_image_stack (IdxT nT) const inline
Definition at line 62 of file Boxxer2D.h.
References boxxer::Boxxer2D< FloatT, IdxT >::imsize.
template<class FloatT = float, class IdxT = uint32_t> ScaledImageT boxxer::Boxxer2D< FloatT, IdxT >::make_scaled_image () const inline
Definition at line 63 of file Boxxer2D.h.
References boxxer::Boxxer2D< FloatT, IdxT >::imsize.
template<class FloatT = float, class IdxT = uint32_t> ScaledImageStackT boxxer::Boxxer2D< FloatT, IdxT >::make_scaled_image_stack (IdxT nT) const inline
Definition at line 64 of file Boxxer2D.h.
References boxxer::Boxxer2D< FloatT, IdxT >::checkMaxima(), boxxer::Boxxer2D< FloatT, IdxT >::enumerateImageMaxima(), boxxer::Boxxer2D< FloatT, IdxT >::filterDoG(), boxxer::Boxxer2D< FloatT, IdxT >::filterGauss(), boxxer::Boxxer2D< FloatT, IdxT >::filterLoG(), and boxxer::Boxxer2D< FloatT, IdxT >::imsize.
template<class FloatT = float, class IdxT = uint32_t> IdxT boxxer::Boxxer2D< FloatT, IdxT >::scaleSpaceDoGMaxima (const ImageStackT & im, IMatT & maxima, VecT & max_vals, IdxT neighborhood_size, IdxT scale_neighborhood_size) const
template<class FloatT = float, class IdxT = uint32_t> IdxT boxxer::Boxxer2D< FloatT, IdxT >::scaleSpaceLoGMaxima (const ImageStackT & im, IMatT & maxima, VecT & max_vals, IdxT neighborhood_size, IdxT scale_neighborhood_size) const
template<class FloatT = float, class IdxT = uint32_t> void boxxer::Boxxer2D< FloatT, IdxT >::setDoGSigmaRatio (FloatT sigma_ratio)
Member Data Documentation
template<class FloatT = float, class IdxT = uint32_t> const FloatT boxxer::Boxxer2D< FloatT, IdxT >::DefaultSigmaRatio static
Definition at line 45 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> const IdxT boxxer::Boxxer2D< FloatT, IdxT >::dim static
Definition at line 46 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> IVecT boxxer::Boxxer2D< FloatT, IdxT >::imsize
Definition at line 49 of file Boxxer2D.h.
Referenced by boxxer::Boxxer2D< FloatT, IdxT >::make_image(), boxxer::Boxxer2D< FloatT, IdxT >::make_image_stack(), boxxer::Boxxer2D< FloatT, IdxT >::make_scaled_image(), and boxxer::Boxxer2D< FloatT, IdxT >::make_scaled_image_stack().
template<class FloatT = float, class IdxT = uint32_t> IdxT boxxer::Boxxer2D< FloatT, IdxT >::nScales
Definition at line 48 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> MatT boxxer::Boxxer2D< FloatT, IdxT >::sigma
Definition at line 50 of file Boxxer2D.h.
template<class FloatT = float, class IdxT = uint32_t> FloatT boxxer::Boxxer2D< FloatT, IdxT >::sigma_ratio
Definition at line 51 of file Boxxer2D.h.
The documentation for this class was generated from the following file:
Boxxer2D.h