Boxxer: boxxer::Boxxer3D< FloatT, IdxT > Class Template Reference
boxxer::Boxxer3D< FloatT, IdxT > Class Template Reference
#include </home/travis/build/markjolah/Boxxer/include/Boxxer/Boxxer3D.h>
Public Types
using IVecT = arma::Col< IdxT >
using IMatT = arma::Mat< IdxT >
using VecT = arma::Col< FloatT >
using MatT = arma::Mat< FloatT >
using ImageT = arma::Cube< FloatT >
using ImageStackT = hypercube::Hypercube< FloatT >
using ScaledImageT = hypercube::Hypercube< FloatT >
Public Member Functions
Boxxer3D (const IVecT &size, const MatT &sigma)
void setDoGSigmaRatio (FloatT sigma_ratio)
void filterScaledLoG (const ImageT &im, ScaledImageT &fim)
void filterScaledDoG (const ImageT &im, ScaledImageT &fim)
IdxT scaleSpaceLoGMaxima (const ImageStackT &im, IMatT &maxima, VecT &max_vals, IdxT neighborhood_size, IdxT scale_neighborhood_size)
IdxT scaleSpaceDoGMaxima (const ImageStackT &im, IMatT &maxima, VecT &max_vals, IdxT neighborhood_size, IdxT scale_neighborhood_size)
ImageT make_image () const
ImageStackT make_image_stack (IdxT nT) const
ScaledImageT make_scaled_image () const
Static Public Member Functions
static void filterLoG (const ImageStackT &im, ImageStackT &fim, const VecT &sigma)
static void filterDoG (const ImageStackT &im, ImageStackT &fim, const VecT &sigma, FloatT sigma_ratio)
static void filterGauss (const ImageStackT &im, ImageStackT &fim, const VecT &sigma)
static void checkMaxima (const ImageStackT &im, IMatT &maxima, VecT &max_vals)
static IdxT enumerateImageMaxima (const ImageStackT &im, IMatT &maxima, VecT &max_vals, IdxT neighborhood_size)
Public Attributes
IdxT nScales
IVecT imsize
MatT sigma
FloatT sigma_ratio
Static Public Attributes
static const FloatT DefaultSigmaRatio
static const IdxT dim
Detailed Description
template<class FloatT = float, class IdxT = uint32_t>
class boxxer::Boxxer3D< FloatT, IdxT >
A box finding algorithm for 3D hyper-spectral microscopy data.
Estimates the center coordinates of Gaussian blobs with anisotropic sigmas.
All image data manipulated is stored as column-major FloatT arrays with dimension ordering [L Y X T].
The Boxxer3D class makes uses of lower level class which are agnostic about the data source being hyperspectral, they don't care what the coordinate dimensions represent scientifically, but this class is associated with the Matlab Boxxer3D class and so maintains the knowledge that the actual coordinates are [L Y X T].
Definition at line 27 of file Boxxer3D.h.
Member Typedef Documentation
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer3D< FloatT, IdxT >::ImageStackT = hypercube::Hypercube<FloatT>
Definition at line 35 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer3D< FloatT, IdxT >::ImageT = arma::Cube<FloatT>
Definition at line 34 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer3D< FloatT, IdxT >::IMatT = arma::Mat<IdxT>
Definition at line 31 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer3D< FloatT, IdxT >::IVecT = arma::Col<IdxT>
Definition at line 30 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer3D< FloatT, IdxT >::MatT = arma::Mat<FloatT>
Definition at line 33 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer3D< FloatT, IdxT >::ScaledImageT = hypercube::Hypercube<FloatT>
Definition at line 36 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> using boxxer::Boxxer3D< FloatT, IdxT >::VecT = arma::Col<FloatT>
Definition at line 32 of file Boxxer3D.h.
Constructor & Destructor Documentation
template<class FloatT = float, class IdxT = uint32_t> boxxer::Boxxer3D< FloatT, IdxT >::Boxxer3D (const IVecT & size, const MatT & sigma)
Member Function Documentation
template<class FloatT = float, class IdxT = uint32_t> static void boxxer::Boxxer3D< FloatT, IdxT >::checkMaxima (const ImageStackT & im, IMatT & maxima, VecT & max_vals) static
Referenced by boxxer::Boxxer3D< FloatT, IdxT >::make_scaled_image().
template<class FloatT = float, class IdxT = uint32_t> static IdxT boxxer::Boxxer3D< FloatT, IdxT >::enumerateImageMaxima (const ImageStackT & im, IMatT & maxima, VecT & max_vals, IdxT neighborhood_size) static
Referenced by boxxer::Boxxer3D< FloatT, IdxT >::make_scaled_image().
template<class FloatT = float, class IdxT = uint32_t> static void boxxer::Boxxer3D< FloatT, IdxT >::filterDoG (const ImageStackT & im, ImageStackT & fim, const VecT & sigma, FloatT sigma_ratio) static
Referenced by boxxer::Boxxer3D< FloatT, IdxT >::make_scaled_image().
template<class FloatT = float, class IdxT = uint32_t> static void boxxer::Boxxer3D< FloatT, IdxT >::filterGauss (const ImageStackT & im, ImageStackT & fim, const VecT & sigma) static
Referenced by boxxer::Boxxer3D< FloatT, IdxT >::make_scaled_image().
template<class FloatT = float, class IdxT = uint32_t> static void boxxer::Boxxer3D< FloatT, IdxT >::filterLoG (const ImageStackT & im, ImageStackT & fim, const VecT & sigma) static
Referenced by boxxer::Boxxer3D< FloatT, IdxT >::make_scaled_image().
template<class FloatT = float, class IdxT = uint32_t> void boxxer::Boxxer3D< FloatT, IdxT >::filterScaledDoG (const ImageT & im, ScaledImageT & fim)
template<class FloatT = float, class IdxT = uint32_t> void boxxer::Boxxer3D< FloatT, IdxT >::filterScaledLoG (const ImageT & im, ScaledImageT & fim)
template<class FloatT = float, class IdxT = uint32_t> ImageT boxxer::Boxxer3D< FloatT, IdxT >::make_image () const inline
Definition at line 55 of file Boxxer3D.h.
References boxxer::Boxxer3D< FloatT, IdxT >::imsize.
template<class FloatT = float, class IdxT = uint32_t> ImageStackT boxxer::Boxxer3D< FloatT, IdxT >::make_image_stack (IdxT nT) const inline
Definition at line 56 of file Boxxer3D.h.
References boxxer::Boxxer3D< FloatT, IdxT >::imsize.
template<class FloatT = float, class IdxT = uint32_t> ScaledImageT boxxer::Boxxer3D< FloatT, IdxT >::make_scaled_image () const inline
Definition at line 57 of file Boxxer3D.h.
References boxxer::Boxxer3D< FloatT, IdxT >::checkMaxima(), boxxer::Boxxer3D< FloatT, IdxT >::enumerateImageMaxima(), boxxer::Boxxer3D< FloatT, IdxT >::filterDoG(), boxxer::Boxxer3D< FloatT, IdxT >::filterGauss(), boxxer::Boxxer3D< FloatT, IdxT >::filterLoG(), and boxxer::Boxxer3D< FloatT, IdxT >::imsize.
template<class FloatT = float, class IdxT = uint32_t> IdxT boxxer::Boxxer3D< FloatT, IdxT >::scaleSpaceDoGMaxima (const ImageStackT & im, IMatT & maxima, VecT & max_vals, IdxT neighborhood_size, IdxT scale_neighborhood_size)
template<class FloatT = float, class IdxT = uint32_t> IdxT boxxer::Boxxer3D< FloatT, IdxT >::scaleSpaceLoGMaxima (const ImageStackT & im, IMatT & maxima, VecT & max_vals, IdxT neighborhood_size, IdxT scale_neighborhood_size)
template<class FloatT = float, class IdxT = uint32_t> void boxxer::Boxxer3D< FloatT, IdxT >::setDoGSigmaRatio (FloatT sigma_ratio)
Member Data Documentation
template<class FloatT = float, class IdxT = uint32_t> const FloatT boxxer::Boxxer3D< FloatT, IdxT >::DefaultSigmaRatio static
Definition at line 38 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> const IdxT boxxer::Boxxer3D< FloatT, IdxT >::dim static
Definition at line 39 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> IVecT boxxer::Boxxer3D< FloatT, IdxT >::imsize
Definition at line 42 of file Boxxer3D.h.
Referenced by boxxer::Boxxer3D< FloatT, IdxT >::make_image(), boxxer::Boxxer3D< FloatT, IdxT >::make_image_stack(), and boxxer::Boxxer3D< FloatT, IdxT >::make_scaled_image().
template<class FloatT = float, class IdxT = uint32_t> IdxT boxxer::Boxxer3D< FloatT, IdxT >::nScales
Definition at line 41 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> MatT boxxer::Boxxer3D< FloatT, IdxT >::sigma
Definition at line 43 of file Boxxer3D.h.
template<class FloatT = float, class IdxT = uint32_t> FloatT boxxer::Boxxer3D< FloatT, IdxT >::sigma_ratio
Definition at line 45 of file Boxxer3D.h.
The documentation for this class was generated from the following file:
Boxxer3D.h