Boxxer: boxxer::kernels Namespace Reference
boxxer::kernels Namespace Reference
Functions
1D Gauss FIR Filters
1D Gaussian finite-impulse response filters.
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_1D (IntT size, const FloatT data[], FloatT fdata[], IntT hw, const FloatT kernel[])
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_1D (const arma::Col< FloatT > &data, arma::Col< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_1D_small (IntT size, const FloatT data[], FloatT fdata[], IntT hw, const FloatT kernel[])
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_1D_arma (const arma::Col< FloatT > &data, arma::Col< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_1D_inplace_arma (arma::Col< FloatT > &data, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_1D_inplace (IntT size, FloatT data[], IntT hw, const FloatT kernel[])
2D Gauss FIR Filters
2D Gaussian finite-impulse response filters.
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_2Dx (const arma::Mat< FloatT > &data, arma::Mat< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_2Dx_small (const arma::Mat< FloatT > &data, arma::Mat< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_2Dx_arma (const arma::Mat< FloatT > &data, arma::Mat< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_2Dy (const arma::Mat< FloatT > &data, arma::Mat< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_2Dy_rowmajor (const arma::Mat< FloatT > &data, arma::Mat< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_2Dy_colmajor (const arma::Mat< FloatT > &data, arma::Mat< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_2Dy_small (const arma::Mat< FloatT > &data, arma::Mat< FloatT > &fdata, const arma::Col< FloatT > &kernel)
3D Gauss FIR Filters
3D Gaussian finite-impulse response filters.
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_3Dx (const arma::Cube< FloatT > &data, arma::Cube< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_3Dx_small (const arma::Cube< FloatT > &data, arma::Cube< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_3Dy (const arma::Cube< FloatT > &data, arma::Cube< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_3Dy_small (const arma::Cube< FloatT > &data, arma::Cube< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_3Dz (const arma::Cube< FloatT > &data, arma::Cube< FloatT > &fdata, const arma::Col< FloatT > &kernel)
template<class FloatT = float, class IntT = int32_t>
void gaussFIR_3Dz_small (const arma::Cube< FloatT > &data, arma::Cube< FloatT > &fdata, const arma::Col< FloatT > &kernel)
Detailed Description
Gaussian finite-impulse response kernels: 1D, 2D, and 3D
Template parameters for all namespace member functions. FloatT - float (default) or double. IntT - signed integer: int32_t (default) or int64_t.
All kernels are explicitly instantiated for:
FloatT = float, IntT = int32_t
FloatT = double, IntT = int32_t
There is no testing for integer overflow. Probably int32_t will be sensible for most applications.
Function Documentation
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_1D (IntT size, const FloatT data[], FloatT fdata[], IntT hw, const FloatT kernel[])
This is details?
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_1D (const arma::Col< FloatT > & data, arma::Col< FloatT > & fdata, const arma::Col< FloatT > & kernel)
This is details?
Definition at line 39 of file FilterKernels.h.
References gaussFIR_1D_arma(), gaussFIR_1D_inplace(), gaussFIR_1D_inplace_arma(), gaussFIR_1D_small(), gaussFIR_2Dx(), gaussFIR_2Dx_arma(), gaussFIR_2Dx_small(), gaussFIR_2Dy(), gaussFIR_2Dy_colmajor(), gaussFIR_2Dy_rowmajor(), gaussFIR_2Dy_small(), gaussFIR_3Dx(), gaussFIR_3Dx_small(), gaussFIR_3Dy(), gaussFIR_3Dy_small(), gaussFIR_3Dz(), and gaussFIR_3Dz_small().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_1D_arma (const arma::Col< FloatT > & data, arma::Col< FloatT > & fdata, const arma::Col< FloatT > & kernel)
This is details?
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_1D_inplace (IntT size, FloatT data[], IntT hw, const FloatT kernel[])
This is details?
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_1D_inplace_arma (arma::Col< FloatT > & data, const arma::Col< FloatT > & kernel)
This is details?
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_1D_small (IntT size, const FloatT data[], FloatT fdata[], IntT hw, const FloatT kernel[])
This is details?
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_2Dx (const arma::Mat< FloatT > & data, arma::Mat< FloatT > & fdata, const arma::Col< FloatT > & kernel)
2D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_2Dx_arma (const arma::Mat< FloatT > & data, arma::Mat< FloatT > & fdata, const arma::Col< FloatT > & kernel)
2D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_2Dx_small (const arma::Mat< FloatT > & data, arma::Mat< FloatT > & fdata, const arma::Col< FloatT > & kernel)
2D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_2Dy (const arma::Mat< FloatT > & data, arma::Mat< FloatT > & fdata, const arma::Col< FloatT > & kernel)
2D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_2Dy_colmajor (const arma::Mat< FloatT > & data, arma::Mat< FloatT > & fdata, const arma::Col< FloatT > & kernel)
2D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_2Dy_rowmajor (const arma::Mat< FloatT > & data, arma::Mat< FloatT > & fdata, const arma::Col< FloatT > & kernel)
2D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_2Dy_small (const arma::Mat< FloatT > & data, arma::Mat< FloatT > & fdata, const arma::Col< FloatT > & kernel)
2D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_3Dx (const arma::Cube< FloatT > & data, arma::Cube< FloatT > & fdata, const arma::Col< FloatT > & kernel)
3D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_3Dx_small (const arma::Cube< FloatT > & data, arma::Cube< FloatT > & fdata, const arma::Col< FloatT > & kernel)
3D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_3Dy (const arma::Cube< FloatT > & data, arma::Cube< FloatT > & fdata, const arma::Col< FloatT > & kernel)
3D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_3Dy_small (const arma::Cube< FloatT > & data, arma::Cube< FloatT > & fdata, const arma::Col< FloatT > & kernel)
3D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_3Dz (const arma::Cube< FloatT > & data, arma::Cube< FloatT > & fdata, const arma::Col< FloatT > & kernel)
3D Gauss FIR Filters
Referenced by gaussFIR_1D().
template<class FloatT = float, class IntT = int32_t> void boxxer::kernels::gaussFIR_3Dz_small (const arma::Cube< FloatT > & data, arma::Cube< FloatT > & fdata, const arma::Col< FloatT > & kernel)
3D Gauss FIR Filters
Referenced by gaussFIR_1D().